### ISSUE TITLE
A question about the evaluation code

### ISSUE THREAD

**Issue by Zhongping-Zhang** [he-dhamo/simsg#10]
Hello,

Thank you for sharing the code for this great project!

I have a question about the ROI experiment. 
In "scripts/evaluate_changes_clevr.py" and "scripts/evaluate_reconstruction.py",  https://github.com/he-dhamo/simsg/blob/31df608cd04facb2b8b546cc6f53d84716117bdf/scripts/evaluate_changes_clevr.py#L413
https://github.com/he-dhamo/simsg/blob/31df608cd04facb2b8b546cc6f53d84716117bdf/scripts/evaluate_reconstruction.py#L236
it seems that ROI focuses on the first object (s==0). From my understanding, ROI should focus on the modified object (corresponds to "new_ids" in the code). Is this for any other specific purpose or did I miss something in the code?

Thank you very much for you time!

**Comment by azadef** [comment]
Thank you for noticing and mentioning the issue. We fixed the code in evaluate_changes_clevr.py and changed "s" to "subject_node". However, the similar code in evaluate_reconstruction is correct since imgs.shape[0] corresponds to the objects in the scene and not the batch number after applying the process_batch function.
